title: Status Page example
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://example.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: My Old Mutual Mobile App
      description: The frontend for the application.
      category: System Components
      link: https://example.com/
    - name: Old Mutual Whatsapp Banking
      description: The bot of the whatsapp application.
      category: System Components
    - name: Oldmutual.co.za
      description: Old mutual South African website
      category: System Components
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#009677"
  enableLastMod: false
  headerTextColor: white
  logo: grafana_logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#ffffff"
  categories:
    - name: System Components
      closed: true
      untitled: true
  description: This is an example of a status page
  enableCustomHTML: true
  useLargeHeaderDesign: false
